/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 goldcrown.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Goldcrown(props) {
  const { nodes, materials } = useGLTF(
    `${process.env.PUBLIC_URL}/goldcrown.gltf`
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.chmch_crown05}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.chmch_crown04}
        />
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.chmch_crown01}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.chmch_crown03}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.chmch_crown02}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.chmch_crown02}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/goldcrown.gltf');
