/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 hemisphericalSundial.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function HemisphericalSundial(props) {
  const { nodes, materials } = useGLTF(
    `${process.env.PUBLIC_URL}/hemisphericalSundial.gltf`
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Hemispherical_Sundial}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/hemisphericalSundial.gltf');
