/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Jagyeongru.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Jagyeongru(props) {
  const { nodes, materials } = useGLTF(
    `${process.env.PUBLIC_URL}/Jagyeongru.gltf`
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Solid} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Solid} />
      </group>
    </group>
  );
}

useGLTF.preload('/Jagyeongru.gltf');
