/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 stone.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Stone(props) {
  const { nodes, materials } = useGLTF(`${process.env.PUBLIC_URL}/stone.gltf`);
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials.Mat_1} />
    </group>
  );
}

useGLTF.preload('/stone.gltf');
